// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	if(level.ex_camouflage) character\mp_german_winterlight_camo::main();
		else character\mp_german_winterlight::main();
}

precache()
{
	if(level.ex_camouflage) character\mp_german_winterlight_camo::precache();
		else character\mp_german_winterlight::precache();

	if(level.ex_hatmodels) character\mp_hatmodels::mp_german_winter_precache();
}
